AmigoBicho/Projeto-Amigo-Bicho

- Site-Amigo-Bicho/duvidas/css/style.css
> atualizacao

- Site-Amigo-Bicho/home/index.html
> atualizacao do link formulario

- Site-Amigo-Bicho/agenda/css/style.css
- Site-Amigo-Bicho/agenda/index.html
> Responsividade

- Site-Amigo-Bicho/localizacao-abrigo/css/style.css
- Site-Amigo-Bicho/localizacao-abrigo/index.html
> Responsividade da página de localização

- Site-Amigo-Bicho/catalogo/css/style.css
> commitando o css do catálogo

- Site-Amigo-Bicho/catalogo/catalogo2.html
> alterações de páginas html e criação da pagina 2

- Site-Amigo-Bicho/localizacao-abrigo/css/style.css
> finalizando a responsividade da pagina localização

- Site-Amigo-Bicho/agenda/css/style.css
- Site-Amigo-Bicho/agenda/index.html
> atualizando a responsividade do calendario

- Site-Amigo-Bicho/cadastro/css/style.css
- Site-Amigo-Bicho/cadastro/index.html
> atualizando responsividade da página cadastro

- Site-Amigo-Bicho/localizacao-abrigo/css/style.css
> atualizando css de responsividade da página de localizacao

- Site-Amigo-Bicho/doacoes/css/style_doacoes.css
> atualizando responsividade da pagina de doações

- Site-Amigo-Bicho/duvidas/css/style.css
> adcionando responsividade da pag duvidas

- Site-Amigo-Bicho/cadastro/css/style.css
> Adicionando margem no main

- Site-Amigo-Bicho/catalogo/catalogo2.html
- Site-Amigo-Bicho/catalogo/index.html
> Correção dos links da página de catálogo

- Site-Amigo-Bicho/cadastro/css/style.css
> Remoção de comentários

- Site-Amigo-Bicho/formulario/css/style.css
- Site-Amigo-Bicho/formulario/index.html
> Formulario

- Site-Amigo-Bicho/formulario-Enviado/css/style.css
> responsividade do rodapé

- Site-Amigo-Bicho/login/css/style.css
> adcionando responsividade da pág login

- Site-Amigo-Bicho/nossa-história/css/style.css
> adcionando responsividade pág nossa historia

- Site-Amigo-Bicho/rec-senha/css/style.css
> adcionando a responsividade da pag de rec senha

- Site-Amigo-Bicho/requisitos-adocao/css/style.css
- Site-Amigo-Bicho/requisitos-adocao/requisitos.html
> adcionando responsividade na pág de requisitos

- Site-Amigo-Bicho/home/index.html
> finalizando pag home

- Site-Amigo-Bicho/perfil/index.html
> link do forms de adoção
